### ISSUE TITLE
game crashing when i change room offset 

### ISSUE THREAD

**Issue by LiiilsGIT** [jxnxsdev/QustomMenu#1]
https://analyzer.questmodding.com/crashes/oFHK sending this here as BS modding discord told me the crash is related to this mod. basically always crashing when changing the room offset. there is also like 5 other crash logs in there that are the same

**Comment by jxnxsdev** [comment]
Thats an odd crash. Seems to be related to my mod although it doesnt make a lot of sense as it crashes while changing something about a textmesh. I'll look into it

**Comment by jxnxsdev** [comment]
What room offset do you mean exactly? The one for the banners, or something completely unrelated?

**Comment by LiiilsGIT** [comment]
> What room offset do you mean exactly? The one for the banners, or something completely unrelated?

The default Beat Saber room adjust feature. Idk why i said offset lol

**Comment by jxnxsdev** [comment]
Fixed in v1.0.1
